server:
  port: 8085

spring:
  application:
    name: spring-graphql

  datasource:
    url: jdbc:mariadb://localhost:3306/graphql_db
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:migration/v1

  graphql:
    graphiql:
      enabled: true
      path: /graphiql

  datetime:
    scalars:
      local-date-time:
        format: yyyy-MM-dd'T'HH:mm:ss


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true

  threads:
    virtual:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace